Sources/ZIPFoundation/Data+Serialization.swift
Fixes #3 
This should speed up entry removal.
=> Added an optional 'skipCRC32' parameter to 'consumePart'

Sources/ZIPFoundation/Archive+Reading.swift, Sources/ZIPFoundation/Archive+Writing.swift, Sources/ZIPFoundation/Entry.swift, Tests/ZIPFoundationTests/ZIPFoundationFileManagerTests.swift
Fixes #4 
Fixes #6 
Refactored entry removal to avoid seeks and CRC32 checksumming.
Also cleaned up API a bit.
=> Improved Entry Removal Performance

Sources/ZIPFoundation/Archive.swift
Fixes #8 
Used setvbuf to modify the default POSIX read/write buffer and tweaked our `defaultReadChunkSize` constant.
=> Tweak POSIX buffers

Tests/ZIPFoundationTests/ZIPFoundationWritingTests.swift
=> XCTAssertEqualWithAccuracy Warning Fix

Sources/ZIPFoundation/Archive+Writing.swift, Tests/ZIPFoundationTests/ZIPFoundationWritingTests.swift
Fixes #23 
Adds a "file exists" check at the beginning of `addEntry`
=> Non-existant File Error Handling for addEntry

Sources/ZIPFoundation/Archive+Writing.swift, Sources/ZIPFoundation/Data+Compression.swift, Sources/ZIPFoundation/FileManager+ZIP.swift, Tests/ZIPFoundationTests/ZIPFoundationFileManagerTests.swift, Tests/ZIPFoundationTests/ZIPFoundationReadingTests.swift, Tests/ZIPFoundationTests/ZIPFoundationTests.swift, Tests/ZIPFoundationTests/ZIPFoundationWritingTests.swift
* Wraps file attribute values in `NSNumber` (not needed on Darwin but necessary for Linux because of different bridging behaviour)
* Excludes tests that rely on KVO from the Linux test suite
=> Linux Test Suite Improvements

Sources/ZIPFoundation/Archive+Reading.swift, Sources/ZIPFoundation/Archive+Writing.swift, Sources/ZIPFoundation/Archive.swift, Sources/ZIPFoundation/Entry.swift, Sources/ZIPFoundation/FileManager+ZIP.swift, Tests/ZIPFoundationTests/ZIPFoundationFileManagerTests.swift, Tests/ZIPFoundationTests/ZIPFoundationTests.swift, Tests/ZIPFoundationTests/ZIPFoundationWritingTests.swift
Fixes #52 
In this PR, we change the order of extraction to extract all directories first. We also apply different default permissions to directories (`755`) than we do to files (`644`). (Directories are extracted first so that the default directory attributes are set instead of the default file attributes.)
This is done by renaming the existing `defaultPermissions` setting to `defaultFilePermissions`, and introducing a new setting `defaultDirectoryPermissions` and updating the `FileManager.attributes:from:` method to take the entry type into account when returning default permissions. 
- I verified that archives extracted with this tweaked algorithm have exactly the same file and directory permissions as archives extracted with macOS's `unzip` command line tool.
- I've only tested this …
=>  Fix an issue with unpacking files within directories on macOS

Sources/ZIPFoundation/Data+Serialization.swift
Swift 4.1 warning message: 'allocate(bytes:alignedTo:)' is deprecated: renamed to 'allocate(byteCount:alignment:)'
I'm not sure if you want to maintain backwards compatibility for some time, so I changed this function name inside a check on the Swift version.
=> Use new function name to allocate bytes in Swift 4.1

ZIPFoundation.xcodeproj/project.pbxproj
Fixes #75
Pretty small change. This allows ZIPFoundation to be imported and used from iOS app extensions. ZIPFoundation is already only using app extension-safe APIs, so it just required enabling this in the project settings.
* Allows use in app extensions by checking "Allow app extension API only" in framework's project settings
* All tests still pass
=> Allow use in app extensions

Sources/ZIPFoundation/Archive+Reading.swift
Fixes #65
* Temporary workaround for attribute not supported on Linux.
=> Remove FileAttributeKeys not supported in swift-corelibs when unzipping file

Package@swift-4.2.swift
Adds Swift 4.2 support for Swift Package Manager.
Note: when attempting to run tests, I get stuck at `testCreateArchiveAddLargeCompressedEntry`, but this occurs before any of my changes were made.
=> Swift 4.2 support for Swift Package Manager

Package@swift-5.swift, ZIPFoundation.xcodeproj/project.pbxproj
- With this change you can now build ZIPFoundation on macOS with just `swift build`
=> Added Swift 5 package manifest with explicit macOS minimum deployment target version

Sources/ZIPFoundation/Data+Compression.swift
Fixes a crash caused by `provider` closures reading beyond input data size boundaries.
=> Restrict over-eager provider closures during compression

README.md
Fixes #133 
* Replace the misleading sample code for closure-based writing of archives
=> Improve documentation for closure-based writing in the README

Tests/ZIPFoundationTests/ZIPFoundationFileManagerTests.swift, ZIPFoundation.xcodeproj/project.pbxproj
Fixes #140 
* Prepend a custom string in reverse DNS notation to our existing bundle product ID to fix an error that App Store Connect / Xcode emits when trying to upload an app that consumes ZIP Foundation
=> Update Product Bundle Identifier

Sources/ZIPFoundation/Archive+Reading.swift, Sources/ZIPFoundation/Data+Compression.swift, Sources/ZIPFoundation/FileManager+ZIP.swift
Fixes #120 
* Exposed the `skipCRC32` flag when reading/extracting an archive.
Why? Skipping the CRC calculation results in improved performance for users who are not interested in comparing the CRC. 
All tests pass.
I don't have a development environment set up for Linux, so I could not run the tests there.
none
=> Exposed skipCRC32 flag to public API when reading/unzipping an archive.

.github/azure-pipelines.yml, Sources/ZIPFoundation/Archive+Reading.swift, Sources/ZIPFoundation/Archive+Writing.swift, Sources/ZIPFoundation/FileManager+ZIP.swift, Tests/ZIPFoundationTests/ZIPFoundationFileManagerTests.swift, Tests/ZIPFoundationTests/ZIPFoundationProgressTests.swift, Tests/ZIPFoundationTests/ZIPFoundationReadingTests.swift, Tests/ZIPFoundationTests/ZIPFoundationTests.swift
When encountering a broken symlink, a false positive .fileReadNoSuchFile Error was thrown, because we were using FileManager.fileExists() to check file existence. It's perfectly valid (and in my use case essential) to include a broken symlink into a zip archive.
*  Use Url.checkResourceIsReachable() instead
Full test suite on macOS Catalina 10.15.1
None reported before AFAIK.
=> fixed error thrown when encountering a broken symlink

Sources/ZIPFoundation/Archive+Writing.swift, Sources/ZIPFoundation/Archive.swift, Sources/ZIPFoundation/Entry.swift, Sources/ZIPFoundation/FileManager+ZIP.swift
Fixes #63 
* Improves documentation for `preferredEncoding`
* Ensures that paths are encoded as UTF-8 during entry addition
=> Path Encoding

Sources/ZIPFoundation/Data+Compression.swift, Tests/ZIPFoundationTests/ZIPFoundationDataSerializationTests.swift, Tests/ZIPFoundationTests/ZIPFoundationWritingTests.swift
Fixes #155
In the Linux compression path, the code in a few places used a raw pointer obtained by `withUnsafeMutableByes` *outside* of the closure argument passed to that function. This is not a correct use of that API, and in fact, I've observed in some situation that compression failed because the data pointed to changed between the call to `withUnsafeMutableBytes` and the use.
The fix is simply to nest the code using the data inside the closure argument. This looks a bit uglier due to the deeper nesting, but no longer exhibits the problems I saw earlier.
Ran unit tests, and used the modified code in my app.
=> Memory safety fix

Sources/ZIPFoundation/Archive.swift, Sources/ZIPFoundation/Entry.swift
Fixes #158
* Wrap `UnsafeBufferPointer` usage in `withUnsafePointer` to guarantee valid pointers when appending to `data`
=> Dangling Buffer Pointer Warnings

Sources/ZIPFoundation/Archive.swift, Sources/ZIPFoundation/Entry.swift
Fixes #179
We used the wrong cast order during calculation of the additional data length. This could potentially lead to an overflow when adding up extra data length fields.
=> Avoid integer overflows when calculation additional data length

README.md
* Using a trailing slash causes issues on some CI systems (i.e. Circle-CI), therefore I've made a change to documentation for this.
=> Fixing trailing slash in Swift Package Dependencies

Sources/ZIPFoundation/Archive.swift
Fixes #181
* Small code refinement that should speed up subscripting via `path`
=> Use `first(where: )` instead of `filter` when subscripting

.github/azure-pipelines.yml, Sources/ZIPFoundation/Archive+Writing.swift
* Do not allow "deflate" compression to be used on Directories and Symlinks headers, as this makes an invalid ZIP file
* Zipped a directory with symlinks
* Tried to "unzip" it from CLI/Finder
* Failed
I didn't add an unit test as I don't really know where to begin
None
---------
Hi,
Thanks for your work! I'm using this library to ZIP a macOS framework.
I'm manually using the "Archive" APIs to do so.
Everything works fine with CompressionMode.none but once I try to use .delfate, it breaks.
I'm basically doing it like this:
```
// Add the entry. Do that even if it is a folder, so that an empty folder correctly gets added
try archive.addEntry(with: itemName, relativeTo: basePath, compressionMethod: compressionMethod)
if isDirectory.boolValue {
try recursivelyAddDirectory(archive: archive, …
```
=> Ignore 'deflate' compression on directories and symlinks

Sources/ZIPFoundation/Archive+Writing.swift
* Fix potential UInt16 overflow.
Related: https://github.com/weichsel/ZIPFoundation/pull/180
Maybe unrelated but some users are crashing in writeEndOfCentralDirectory with the following log:
```
0   XXXX                                0x0000000107cdbf08 ZIPFoundation.Archive.(writeEndOfCentralDirectory in _604C70144D53B6896EE0A47AB80823C8)(centralDirectoryStructure: ZIPFoundation.Entry.CentralDirectoryStructure, startOfCentralDirectory: Swift.UInt32, operation: ZIPFoundation.Archive.(ModifyOperation in _604C70144D53B6896EE0A47AB80823C8)) throws -> ZIPFoundation.Archive.EndOfCentralDirectoryRecord (in XXXX) (<compiler-generated>:0)
```
(I could not reproduce the crash.)
=> Fix potential UInt16 overflow

Sources/ZIPFoundation/Archive+Writing.swift, Tests/ZIPFoundationTests/ZIPFoundationTests.swift, Tests/ZIPFoundationTests/ZIPFoundationWritingTests.swift
Fixes #198
* Guard against entry removal from archives initialized with mode `.read` 
* Make the behavior consistent with the `addEntry` method
* Add test coverage for the new error codepath
=> Disallow removal of entries from readonly archives

Sources/ZIPFoundation/Data+Compression.swift
Fixes
Fix incorrect usage of `MemoryLayout.size` for `MemoryLayout.stride`.
[MemoryLayout](https://developer.apple.com/documentation/swift/memorylayout):
> Always use a multiple of a type’s stride instead of its size when allocating memory or accounting for the distance between instances in memory.
Fix incorrect usage of `MemoryLayout.size` for `MemoryLayout.stride`.
=> Fix incorrect usage of MemoryLayout.size for MemoryLayout.stride

Sources/ZIPFoundation/Archive+Writing.swift, Sources/ZIPFoundation/Archive.swift, Sources/ZIPFoundation/Data+Compression.swift, Tests/ZIPFoundationTests/ZIPFoundationTests.swift, Tests/ZIPFoundationTests/ZIPFoundationWritingOverflowTests.swift
Fixes file count overflow.
ZIPFoundation crashes at https://github.com/weichsel/ZIPFoundation/blob/cf10bbff6ac3b873e97b36b9784c79866a051a8e/Sources/ZIPFoundation/Archive%2BWriting.swift#L354 if file count exceeds 65535 (UInt16.max).
* Add overflow check for `NumberOfEntriesOnDisk` and `NumberOfEntriesInCentralDirectory `
An error is thrown instead of crash if file count exceeds 65535.
=> Fix overflow of file count

Sources/ZIPFoundation/Archive+Writing.swift
Fixes crash that can happen if you try to save an archive to Google Drive in streaming mode
* throw instead of crash if fopen returns nil
=> fix crash if fopen returns nil

Sources/ZIPFoundation/Entry+ZIP64.swift, Sources/ZIPFoundation/Entry.swift
Fixes #238
* Preserve existing ZIP extra field data when removing entries
=> Preserve extra field data during entry removal

Sources/ZIPFoundation/Data+Compression.swift
Fixes #229
* Consider edge case where CRC32 checksum was calculated for unfinished compression buffers
=> Fix Invalid CRC32 calculation for non-final compression streams

Sources/ZIPFoundation/Archive+BackingConfiguration.swift, Sources/ZIPFoundation/Archive+MemoryFile.swift, Sources/ZIPFoundation/Archive+Reading.swift, Sources/ZIPFoundation/Archive+Writing.swift, Sources/ZIPFoundation/Archive.swift, Sources/ZIPFoundation/Data+Serialization.swift, Sources/ZIPFoundation/FileManager+ZIP.swift, Tests/ZIPFoundationTests/ZIPFoundationDataSerializationTests.swift, Tests/ZIPFoundationTests/ZIPFoundationReadingTests.swift, Tests/ZIPFoundationTests/ZIPFoundationTests.swift
* Add a `FILEPointer` type alias, as `FILE` is an opaque struct since Android 7.
* Add Android to existing OS specializations where needed.
* Convert to `mode_t` in `FIleManager+ZIP` for Android armv7, where `mode_t` is narrower than `st_mode`.
I ran `swift test` on both linux x86_64 and Android AArch64 with this pull and all tests passed. 
I used this pull when porting CookCLI as a package for Android, termux/termux-packages#11081. I used a similar typealias when porting apple/swift-tools-support-core#243 for Android last year.
None
=> Port to Android

Sources/ZIPFoundation/Data+Serialization.swift
Fixes #268 
The goal of this PR is to make the `DataError` type `public` so that allowing the developers to handle this type of error in their apps.
=> Make the `DataError` type `public`

Package@swift-4.0.swift, Sources/ZIPFoundation/Archive+MemoryFile.swift, Sources/ZIPFoundation/Archive+Writing.swift, Sources/ZIPFoundation/Data+Compression.swift, Sources/ZIPFoundation/Date+ZIP.swift, Sources/ZIPFoundation/FileManager+ZIP.swift, Tests/ZIPFoundationTests/ZIPFoundationFileAttributeTests.swift, Tests/ZIPFoundationTests/ZIPFoundationProgressTests.swift, Tests/ZIPFoundationTests/ZIPFoundationTests.swift
This PR Adds the os(xrOS) conditional check, without it the build fails as it falls into the #else block.
This is required to build with Xcode 15 beta 6
=> Fixes so repo builds with Xcode 15

.github/workflows/swift.yml, Sources/ZIPFoundation/Archive+BackingConfiguration.swift, Sources/ZIPFoundation/Archive+Deprecated.swift, Sources/ZIPFoundation/Archive+Writing.swift, Sources/ZIPFoundation/Archive.swift, Sources/ZIPFoundation/FileManager+ZIP.swift, Sources/ZIPFoundation/FileManager+ZIPDeprecated.swift, Tests/ZIPFoundationTests/ZIPFoundationArchiveTests.swift, Tests/ZIPFoundationTests/ZIPFoundationDataSerializationTests.swift, Tests/ZIPFoundationTests/ZIPFoundationErrorConditionTests+ZIP64.swift, Tests/ZIPFoundationTests/ZIPFoundationErrorConditionTests.swift, Tests/ZIPFoundationTests/ZIPFoundationFileAttributeTests.swift, Tests/ZIPFoundationTests/ZIPFoundationFileManagerTests+ZIP64.swift, Tests/ZIPFoundationTests/ZIPFoundationFileManagerTests.swift, Tests/ZIPFoundationTests/ZIPFoundationMemoryTests.swift, Tests/ZIPFoundationTests/ZIPFoundationProgressTests.swift, Tests/ZIPFoundationTests/ZIPFoundationReadingTests.swift, Tests/ZIPFoundationTests/ZIPFoundationTests.swift, Tests/ZIPFoundationTests/ZIPFoundationWritingTests.swift, ZIPFoundation.xcodeproj/project.pbxproj
Fixes #126
Fixes #242
* Makes `Archive` initializers throwing
*  Adds early-exit codepath when encountering non-ZIP files
=> Throwing Archive Init

Sources/ZIPFoundation/Archive+Writing.swift
Fixes #
Provides the file with permissions lacking, not the url of the zip archive, in the error thrown.
* 
* 
* 
* all of them (Ran tests after change)
The current behavior is to throw an error when adding an entry to a zip file that cannot be read. This is perfectly reasonable, but the error thrown gives the url of the zip file, not the file with a permission error. The fix simply provides the newly added (or attempted, more like) file url, not the url of the zip file.
=> (fix) provides correct file url in thrown error with permission error

Package@swift-5.9.swift
Fixes #
* Swift tools v 5.9 generate warnings during compilation because the supported platform versions are set lower than it is allowed. The proposed platform versions are as follows:
- macOS: 10.13 (changed from: 10.11)
- iOS: 11.0  (changed from: 9.0)
- tvOS: 11..  (changed from: 9.0)
- watchOS: 4.0  (changed from: 2)
- visionOS: 1.0 (unchanged)
Performed a clean build and the warnings are now gone.
This change only affects Swift 5.9 and has no effect on previous versions.
=> Updated platform requirements in Package@swift-5.9.swift

Package@swift-5.9.swift
Fixes #
`swift package` CLI throws a warning that `v11` is too hold for swift-5.9
```
warning: 'zipfoundation': /Package@swift-5.9.swift:23:32: warning: 'v11' is deprecated: iOS 12.0 is the oldest supported version
.macOS(.v10_13), .iOS(.v11), .tvOS(.v11), .watchOS(.v4), .visionOS(.v1)
^
/Package@swift-5.9.swift:23:45: warning: 'v11' is deprecated: tvOS 12.0 is the oldest supported version
.macOS(.v10_13), .iOS(.v11), .tvOS(.v11), .watchOS(.v4), .visionOS(.v1)
^
```
* 
* 
*
=> Update Package@swift-5.9.swift platform info

Sources/ZIPFoundation/Resources/PrivacyInfo.xcprivacy, ZIPFoundation.podspec
Fixes two issues related to the privacy manifest:
1. The manifest itself is kind of invalid (as discussed in #313)
Including a NSPrivacyCollectedDataTypes entry but specifying empty strings is incorrect. Instead, you can just specify an empty array for NSPrivacyCollectedDataTypes at the top level. Also, the top level NSPrivacyTracking and NSPrivacyTrackingDomains keys were missing; I've added them with false/empty values as appropriate.
2. The podspec reference for the privacy manifest was problematic.
When static framework linking is used with Cocoapods, files referenced using `resource` are just directly copied into the main app bundle, potentially clobbering each other or main app resources in the process. i.e., the PrivacyInfo.xcprivacy from ZIPFoundation can overwrite the one for the …
=> Fix privacy manifest issues

.github/workflows/CI.yml, README.md, Sources/ZIPFoundation/Archive.swift
Fixes Linux GitHub Actions jobs
=> Update GitHub workflow

Sources/ZIPFoundation/Data+Serialization.swift
There is a memory leak in `Data.readChunk` when `fread` fails to read data.
This PR fixes it by deallocating memory before throwing an exception.
I didn't create an issue for this, as the problem is obvious, but please let me know if an issue is needed.
=> Fix a possible memory leak in Data.readChunk

Sources/ZIPFoundation/Archive+BackingConfiguration.swift
An exception is thrown before closing a FILE, causing a resource leak.
This PR adds a call to fclose before throwing the exception to fix the leak.
=> Fix resource leak in `Archive#makeBackingConfiguration`

Sources/ZIPFoundation/Data+Serialization.swift
Fixes #
Recently when testing a nightly Swift snapshot in a project of mine, I came across an alignment crash. It turns out that
1. There is no guarantee that `Data` or `subdata` point to memory with any particular alignment.
2. In this configuration, with `T` being `UInt32`, the `subdata` was in fact *inline* data, which is always aligned on a 2 byte boundary but misaligned for 4 bytes.
3. When compiling in debug mode, `load` checks for proper alignment and aborts in this case.
The solution is to use the `loadUnaligned` call which makes no alignment assumptions.
All unit tests keep passing.
Unfortunately, I have no good isolated reproduction case for the crash, nor can I be more specific about the project in question.
=> Fix alignment crash in debug mode

Sources/ZIPFoundation/FileManager+ZIP.swift, Tests/ZIPFoundationTests/ZIPFoundationTests.swift
* Adds support for the `.fileModification` attribute on non-Darwin platforms
=> Set modification date on non-Darwin platforms
